version: 0.2

env:
  variables:
      $TEST: "{$CODEBUILD_BUILD_ARN}"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes

phases:
  install:
    #Ubuntu 標準イメージ 2.0 以降を使用する場合、ランタイムバージョンを指定する必要があります。
    #ランタイムバージョンを指定して、Ubuntu 標準イメージ 2.0 以外のイメージを使用すると、ビルドは失敗します。
    runtime-versions:
      #golang: 1.x
       docker: 18.x
    #commands:
       #- go get golang.org/x/lint/golint
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       #- golint -set_exit_status ./...
       - docker build -t katsumata-test:1.0 .
       - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 385606461848.dkr.ecr.ap-northeast-1.amazonaws.com
       - docker tag katsumata-test:1.0 385606461848.dkr.ecr.ap-northeast-1.amazonaws.com/katsumata-test:1.0
       - docker push 385606461848.dkr.ecr.ap-northeast-1.amazonaws.com/katsumata-test:1.0
      # - command